import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ContactForm from "../components/contact-form";

export default function Home() {
  return (
    <div className={styles.container}>

    
      <Head>
      {/* name in tabs - browser */}
        <title>Matt Playne</title>
        <meta name="description" content="Generated by create next app" />
        {/* icon infront of name with link  */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className={styles.logo}>
          Matt Playne (logo)
        </p>
      <div className={styles.nav}>
        <a href="#music">Music </a>
        <a href="#booking">Booking </a>
        <a href="#lessons">Lessons</a>
        </div>

      <main className={styles.main}>
        
        
        
        {/* <h1 className={styles.title}>
          Matt Playne
        </h1> */}
        

        <section className={styles.video}>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/GN-BfRMJGLU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </section>


        
        <p className={styles.description}>
          About - Matt Playne is a singer-songwriter. Book him for your wedding and private or public events. -- Click Here
        </p>
        
        <div className={styles.form}>
        <ContactForm />
        </div>


        <section className={styles.booking}>
        <h2 className={styles.description}>
          Booking
        </h2>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Weddings &rarr;</h2>
            
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Private Events &rarr;</h2>
            
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Bars & Taverns &rarr;</h2>
            
          </a>

          
        </div>
        </section>


        <section className={styles.lessons}>
        <h2 className={styles.description}>
          Lessons
        </h2>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Voice &rarr;</h2>
            
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Voice & Guitar &rarr;</h2>
            
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Performance &rarr;</h2>
            
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Recording & Mixing &rarr;</h2>

          </a>
        </div>
        </section>



      </main>

      <footer className={styles.footer}>
        Created by Matt Playne
      </footer>
    </div>
  )
}
