import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ContactForm from "../components/Form";
import Footer from '../components/Footer';
import Navbar from '../components/Navbar';
import Video from '../components/Video';
import About from '../components/About';

export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
      {/* name in tabs - browser */}
        <title>Matt Playne</title>
        <meta name="description" content="Generated by create next app" />
        {/* icon infront of name with link  */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={styles.main}>
        
        <Video />
        
        {/* <h1 className={styles.title}>
          Matt Playne
        </h1> */}
        <About />
        
        {/* <p className={styles.description}>
          About - Matt Playne is a singer-songwriter. Book him for your wedding and private or public events. -- Click Here
        </p> */}
        
    
        <ContactForm />
       


        <section className={styles.booking}>
        <h2 className={styles.description}>
          Booking
        </h2>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Weddings &rarr;</h2>
            
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Private Events &rarr;</h2>
            
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Bars & Taverns &rarr;</h2>
            
          </a>

          
        </div>
        </section>


        <section className={styles.lessons}>
        <h2 className={styles.description}>
          Lessons
        </h2>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Voice &rarr;</h2>
            
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Voice & Guitar &rarr;</h2>
            
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Performance &rarr;</h2>
            
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Recording & Mixing &rarr;</h2>

          </a>
        </div>
        </section>



      </main>
        <Footer />
     
    </div>
  )
}
